In [2]:
print('Hello world!!')

Hello world!!


### Import biblioteki NumPY

In [3]:
import numpy as np

### Pierwsze tablice NumPy

Tablica 1D

In [4]:
arr1d = np.array([1, 2, 3])

In [5]:
arr1d

array([1, 2, 3])

In [6]:
type(arr1d)

numpy.ndarray

Tablica 2D

In [9]:
arr2d = np.array([[1, 2], [3, 4], [5, 6]])
arr2d

array([[1, 2],
       [3, 4],
       [5, 6]])

Tablica 3D

In [11]:
arr3d = np.array([[[1, 2], [2, 3]], [[4, 5], [6, 7]]])
arr3d

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Wymiar tablic

In [12]:
arr1d.ndim

1

In [13]:
arr2d.ndim

2

In [14]:
arr3d.ndim

3

Kształty tablicy

In [15]:
arr1d.shape

(3,)

In [16]:
arr2d.shape

(3, 2)

In [17]:
arr3d.shape

(2, 2, 2)

Typy danych

In [18]:
arr1d.dtype

dtype('int32')

In [19]:
arr_float = np.array([1.1, 2.9])
arr_float

array([1.1, 2.9])

In [20]:
arr_float.dtype

dtype('float64')

In [21]:
arr_bool = np.array([True, False])
arr_bool

array([ True, False])

In [22]:
arr_bool.dtype

dtype('bool')

In [27]:
arr_int = np.array([1.5, 2.4],dtype='int')
arr_int

array([1, 2])

In [28]:
arr_int.dtype

dtype('int32')

### Funkcje tworzące tablice

In [29]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [34]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [40]:
np.linspace(0, 10, 50) # start , koniec, ilość punktów

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [42]:
np.full([3, 2], 3)

array([[3, 3],
       [3, 3],
       [3, 3]])

### Podstawowe operacje na tablicach

In [43]:
a = np.array([3, 4, 5, 6])
b = np.array([-1, 2, 4, 1])

In [44]:
print(a)
print(b)

[3 4 5 6]
[-1  2  4  1]


In [45]:
a + b

array([2, 6, 9, 7])

In [46]:
a - b

array([4, 2, 1, 5])

In [47]:
a * b

array([-3,  8, 20,  6])

In [48]:
a + 1

array([4, 5, 6, 7])

### Generowanie liczb pseudolosowych

In [49]:
np.random.seed(5)

In [52]:
np.random.randn() # rozkład normalny - najwiecej wartości w okół 0 w obie strony

2.43077118700778

In [51]:
np.random.rand() # od 0 -1

0.8707323061773764

In [53]:
np.random.randn(10)

array([-0.25209213,  0.10960984,  1.58248112, -0.9092324 , -0.59163666,
        0.18760323, -0.32986996, -1.19276461, -0.20487651, -0.35882895])

In [54]:
np.random.randint(10, 20)

12

In [55]:
np.random.choice(['a', 'b', 'c', 'd'])

'c'