In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Wybór elementu po indeksie

In [3]:
arr[2]

3

In [4]:
arr[2:5]  # 5 indeks nie wchodzi, indeksy od 0 zaczynaja się

array([3, 4, 5])

In [5]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

Przypisawanie nowej wartości

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
arr[0] = 100
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [9]:
arr[10:12] = 200
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200, 200,  13,
        14,  15])

Zmiana kształtu

In [10]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
arr2d = arr.reshape([3, 5])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Maski logiczne

In [12]:
arr_rnd = np.random.randn(3, 5)
arr_rnd

array([[ 0.55172974,  1.10348752, -0.22319815, -0.38938454, -0.20410693],
       [-0.61531723,  0.11375588, -0.48709298, -0.8962792 ,  0.88308424],
       [-0.08985432,  0.38424998, -0.25673375, -0.0765811 , -0.38275414]])

In [13]:
arr_bool = arr_rnd > 0
arr_bool

array([[ True,  True, False, False, False],
       [False,  True, False, False,  True],
       [False,  True, False, False, False]])

In [14]:
arr_rnd[arr_bool]

array([0.55172974, 1.10348752, 0.11375588, 0.88308424, 0.38424998])

In [16]:
arr_rnd[arr_rnd < 0]

array([-0.22319815, -0.38938454, -0.20410693, -0.61531723, -0.48709298,
       -0.8962792 , -0.08985432, -0.25673375, -0.0765811 , -0.38275414])